name: build-release-image-celery

on:
  push:
    branches:
      - "release/*"

jobs:
  build-release-image-celery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version tag
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./celery_worker/Dockerfile
          push: true
          build-args: |
            VERSION=rc-${{ env.BRANCH }}
          tags: |
            merouaneb/ronin-url-token-celery:latestRelease
            merouaneb/ronin-url-token-celery:rc-${{ env.BRANCH }}